### ISSUE TITLE
Series can't be removed through Java API

### ISSUE THREAD

**Issue by tulioag** [vaadin/vaadin-charts#570] opened 2021-02-24 09:45 UTC
After adding a series
```java
  configuration.addSeries(new ListSeries("Asia", 502, 635, 809, 947, 1402, 3634, 5268));
```
It can not be removed from the chart, except by replacing the configuration object
```java
chart.setConfiguration(new Configuration());
```
I would expect that calling ` configuration.setSeries()` without parameters would work, but all series continue to be displayed.

**Comment by DiegoCardoso** [comment] 2021-05-06 14:17
After discussing this internally, we concluded that making `setSeries` immediately send the changes to the client would be a behavior change not expected by some users.

In order to clean the series, what can be done is
```java
conf.setSeries();
chart.drawChart(true);
```

We will mention that on the javadoc that one needs to call `Chart#drawChart(true)` after `setSeries()` if this is done after the first render of the `Chart` instance in order to have it reflected on the client.

We are also fixing one issue related to `setSeries` as described in #515.

**Comment by knoobie** [comment] 2021-05-06 14:33
@DiegoCardoso Thanks! Having this mentioned in the javadoc is a good trade off.

**Comment by TatuLund** [comment] 2021-05-07 05:48
Does this have the same root cause as this one https://github.com/vaadin/vaadin-charts/issues/515 ?

**Comment by DiegoCardoso** [comment] 2021-05-07 08:12
> Does this have the same root cause as this one #515 ?

Kind of. It needs #515 to be fixed in order to be able to call `addSeries` after `setSeries` is called, but this one is about not having the changes reflected on the client (I am assuming the call for `setSeries` on the OP was done _after_ the chart was rendered).

**Closed** 2021-05-10 14:34 UTC
Labels: BFP, Impact: Low, Severity: Minor, bug
