### ISSUE TITLE
Sparkline kills app when run through polymer-cli

### ISSUE THREAD

**Issue by juniperbelmont** [vaadin/vaadin-charts#131] opened 2016-06-09 23:57 UTC
Following #126 , as of commit 9e28b89, I'm unable to use vaadin-sparkline.

Reproduce:
* Install polymer-cli npm install -g polymer-cli
* Create new directory and go into it
* Run polymer init and choose app-drawer-template
* bower install vaadin-charts#9e28b89
* Include a vaadin-bar-chart in my-view3.html and add this to the template:

`<vaadin-sparkline></vaadin-sparkline>`

* Run app with polymer serve and go to view 3

Error: 

> highstock.js:228 Uncaught TypeError: Cannot read property 'type' of undefined

**Comment by Peppe** [comment] 2016-06-10 06:47
Thank you for your bug report.

As I have not much experience with polymer-cli, I tested it out and created a pure command list to reproduce:
```
npm install -g polymer-cli
mkdir cli-test
cd cli-test
polymer init [choose app-drawer-template in list]
bower install vaadin-charts#9e28b89
polymer serve
```
Open up browser to localhost:8080 to see the app. Open up the source files in your editor of choice and go to file src/myview1.html

At the beginning of file add:
```<link rel="import" href="../bower_components/vaadin-charts/vaadin-sparkline.html">```

Within the template, add:
```<vaadin-sparkline data="1,3,2"></vaadin-sparkline>````

After this you get the error in inspector which is mentioned above. Switching it to a bar chart worked. With the latest stable release, which today points at 3.0.0, neither of them works.

What a vaadin-sparkline is is actually just a preconfigured vaadin-line-chart. The component creates a template for the vaadin-line-chart on the fly and embeds it into vaadin-sparkline. I will still try how it works with using the line-chart correctly, if I can that way find what goes wrong.

**Comment by samiheikki** [comment] 2016-06-10 06:59
@juniperbelmont Can you test it out using `vaadin-charts#task/CHARTS-505` branch? #130 

Looks like `data` attribute is not properly initialized with dynamic importing.

Thanks for the bug report.

**Comment by Peppe** [comment] 2016-06-10 07:18
```
<vaadin-sparkline data="1,3,2"></vaadin-sparkline>
```

is translated into 

```
<vaadin-line-chart id="chart">
  <chart-title text="null"></chart-title>
  <chart margin="0" spacing="0" background-color="null" skip-clone="true"></chart>
  <exporting enabled="false"></exporting>
  <plot-options>
    <line enable-mouse-tracking="false" show-in-legend="false" animation="false" shadow="false">
      <marker enabled="false"></marker>
    </line>
  </plot-options>
  <x-axis line-width="0" minor-grid-line-width="0" minor-tick-length="0" minor-tick-width="0" grid-line-width="0" title="null" max-padding="0" min-padding="0" start-on-tick="false" end-on-tick="false">
    <labels enabled="false"></labels>
  </x-axis>
  <y-axis line-width="0" minor-grid-line-width="0" minor-tick-length="0" minor-tick-width="0" grid-line-width="0" title="null" max-padding="0.1" min-padding="0.1" start-on-tick="false" end-on-tick="false">
    <labels enabled="false"></labels>
  </y-axis>
  <data-series type="line"></data-series>
</vaadin-line-chart>
```
This fails because <data-series> is missing the data.
A workaround is to use the code above but replace the data-series with something containing the actual data:
```
<data-series type="line"><data>1,2,3</data></data-series>
```

**Comment by juniperbelmont** [comment] 2016-06-10 14:39
@samiheikki Hey, #3d812b97d5eb67045c6b119126db3034fdace03c seems to fix the issue.

Thanks!

**Comment by samiheikki** [comment] 2016-06-15 09:45
Fixed in https://github.com/vaadin/vaadin-charts/commit/3d812b97d5eb67045c6b119126db3034fdace03c

**Closed by samiheikki** 2016-06-15 09:45 UTC
